name: YouTube Avatar Scanner

on:
  workflow_dispatch: 
  
jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go get golang.org/x/net

    - name: Run Scanner
      run: go run main.go
