name: Lightshot Scanner

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      PROXY_LIST_URL: https://raw.githubusercontent.com/zilch-fnoop-8842-krag/glorf-nibz-7724-xqpto-muv/refs/heads/flurbo-womplex-4491-zzyzx/valid_proxies.txt
      CONCURRENCY: 100 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Initialize and Download Go modules
      run: |
        go mod init lightshot-scanner
        go mod tidy

    - name: Build scanner
      run: go build -o lightshot-scanner .

    - name: Run scanner
      timeout-minutes: 180
      run: ./lightshot-scanner

    - name: Upload found_images.txt artifact
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: found-lightshot-images
        path: found_images.txt
